version: "3.8"

services:
  db:
    image: percona/percona-server:8.0
    restart: always
    volumes:
      - ./docker-compose/.data/db:/var/lib/mysql:consistent
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - internal

  api:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    networks:
      - internal

networks:
  internal:

